name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build15: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.oututs.duration }}
      env:
        version: 1.5.0
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: echo '::set-output name=duration::${./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in "}'
  summary:
    runs-on: ubuntu-latest
    needs:
      build15
    steps:
      - name: make summary
        run: |
          echo '|version|result|' >> $GITHUB_STEP_SUMMARY
          echo '|---|---|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.0|${{needs.build15.outputs.output}}|' >> $GITHUB_STEP_SUMMARY