name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  summary:
      runs-on: ubuntu-latest
      steps:
        - name: make summary
          run: |
            echo '|version|os|result|' >> $GITHUB_STEP_SUMMARY
            echo '|---|---|---|' >> $GITHUB_STEP_SUMMARY
  build:
    strategy:
      fail-fast: false
      matrix:
        # version: [1.5.0, 1.5.10, 1.5.20, 1.5.21, 1.5.30, 1.5.31, 1.5.32]
        version: [1.5.0, 1.5.10]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    env:
      version: ${{ matrix.version }}
    steps:  
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # - id: build
      #   name: Build with Gradle
      #   run: |
      #     RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
      #     echo '|${{ matrix.version }}|${{ matrix.os }}|${RESULT}|' >> $GITHUB_STEP_SUMMARY
      - if: always()
        id: generate-outputs
        uses: actions/github-script@v6
        with:
          script: |
            const result = await exec.exec('./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'')
            val data = process.env["result"]
            data[${{ matrix.version }}_${{ matrix.os}}] = result
            core.exportVariable(data)
