name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        version: [1.5.0, 1.5.10, 1.5.20, 1.5.21, 1.5.30, 1.5.31, 1.5.32, 1.6.0, 1.6.10, 1.6.20, 1.6.21]
        os: [ubuntu-latest, windows-latest]
    env:
      version: ${{ matrix.version }}
    steps:  
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - if: always()
        run: echo '${{ toJSON(matrix) }}' > ./matrix.txt
      - if: always()
        id: generate-unique-id
        run: echo '::set-output name=result::${{ hashFiles('./matrix.txt') }}'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew bundleDebug bundleRelease --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
      - if: always()
        id: generate-outputs
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const id = "${{ steps.generate-unique-id.outputs.result }}"
            const matrix = ${{ toJSON(matrix) }}
            const status = "${{ job.status }}"
            const exportedValues = "${{ steps.build.outputs.duration }}"
            const outputs = { matrix, status, id, exportedValues }
            fs.writeFileSync("${{ github.workspace }}/outputs.txt", JSON.stringify(outputs))
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: outputs-${{ steps.generate-unique-id.outputs.result }}
          path: ${{ github.workspace }}/outputs.txt
  after-matrix-job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: matrix-job-outputs
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const path = require('path')
            const directory = path.resolve('./matrix-job-outputs')
            const matchedOutputs = [[{data: 'version', header:true}, {data: 'os', header:true}, {data: 'result', header: true}]]
            for (const dirName of fs.readdirSync(directory)) {
              const filePath = path.join(directory, dirName, 'outputs.txt')
              const outputs = JSON.parse(fs.readFileSync(filePath))
              matchedOutputs.push([outputs.matrix.version, outputs.matrix.os, outputs.exportedValues])
            }
            await core.summary
              .addTable(matchedOutputs)
              .write()


  build150: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.0
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1510: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.10
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1520: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.20
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1521: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.21
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1530: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.30
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1531: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.31
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  build1532: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.outputs.duration }}
      env:
        version: 1.5.32
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: |
          RESULT=`./gradlew buildDebug --profile | grep "BUILD SUCCESSFUL in " | sed -e 's/^[^dm"]* //'`
          echo "::set-output name=duration::${RESULT}"
  summary:
    runs-on: ubuntu-latest
    needs: [build150, build1510, build1520, build1521,  build1530, build1531, build1532]
    steps:
      - name: make summary
        run: |
          echo '|version|result|' >> $GITHUB_STEP_SUMMARY
          echo '|---|---|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.0|${{needs.build150.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.10|${{needs.build1510.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.20|${{needs.build1520.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.21|${{needs.build1521.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.30|${{needs.build1530.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.31|${{needs.build1531.outputs.output}}|' >> $GITHUB_STEP_SUMMARY
          echo '|1.5.32|${{needs.build1532.outputs.output}}|' >> $GITHUB_STEP_SUMMARY