name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build15: 
      runs-on: ubuntu-latest
      outputs:
        output: ${{ steps.build.oututs.duration }}
      env:
        version: 1.5.0
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: ./gradlew buildDebug
  build16: 
      runs-on: ubuntu-latest
      outputs:
        output_${{ matrix.version }}: ${{ steps.build.oututs.test }}
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: build
        name: Build with Gradle
        run: ./gradlew build
  build17: 
    runs-on: ubuntu-latest
    outputs:
      output_${{ matrix.version }}: ${{ steps.build.oututs.test }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - id: build
      name: Build with Gradle
      run: ./gradlew build
